---
- hosts: all
  vars_files:
    - defaults/main.yml
    - minimal.config.yml
    - cli_workstation.yml
    - workstation.config.yml

  pre_tasks:
    - name: "Ensure custom facts dir exists"
      ansible.builtin.file:
        path: /etc/ansible/facts.d
        state: directory
        mode: '0755'
      become: true

    - name: "Distribute facts"
      ansible.builtin.copy:
        src: facts/
        dest: /etc/ansible/facts.d/
        mode: '0755'
      become: true

    - name: "Update facts"
      ansible.builtin.setup:

  roles:
    - role: geerlingguy.mac.homebrew
      when: ansible_system == "Darwin"
    - role: geerlingguy.mac.mas
      when: ansible_system == "Darwin"
    - role: geerlingguy.mac.dock
      when: ansible_system == "Darwin"
    - role: zsh
      when: ansible_system == "Darwin" or ansible_system == "Linux"
    - role: aws_cli
    - role: mac_gui
      when: ansible_system == "Darwin"
    - role: minimal_workstation
      when: ansible_system == "Linux"
    - role: cli_workstation
      when: ansible_system == "Linux"
    - role: workstation
      when: ansible_system == "Linux"
