---
- name: Trust 1password gpg
  ansible.builtin.rpm_key:
    state: present
    key: https://downloads.1password.com/linux/keys/1password.asc
  become: True

- name: Add 1Password repository
  ansible.builtin.yum_repository:
    name: 1Password
    description: "1Password Stable Channel"
    baseurl: "https://downloads.1password.com/linux/rpm/stable/$basearch"
    gpgkey: "https://downloads.1password.com/linux/keys/1password.asc"
    state: present
    enabled: True
  become: True

- name: Install 1Password
  ansible.builtin.package:
    name: 1password
    state: latest
  become: True

- name: Install 1Password-cli
  ansible.builtin.package:
    name: 1password-cli
    state: latest
  become: True