---
# tasks file for workstation

- name: Install nerd fonts
  ansible.builtin.unarchive:
    src: "{{ font_download_url }}"
    remote_src: yes
    dest: /usr/share/fonts
  become: true

- name: Set graphical as default target
  ansible.builtin.file:
    src: /usr/lib/systemd/system/graphical.target
    dest: /etc/systemd/system/default.target
    state: link
  become: True

- name: Install KDE
  ansible.builtin.import_tasks: "kde.yml"

- name: Install tmux
  ansible.builtin.import_tasks: "tmux.yml"

- name: Deploy AWS Cli V2
  ansible.builtin.import_tasks: "aws_cli_v2.yml"
