---
- name: Ensure local bin directory exists
  ansible.builtin.file:
    path: "~/.local/bin"
    state: directory
    mode: 0750

- name: install oh my zsh
  ansible.builtin.git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: "~/.oh-my-zsh"
    depth: 1
    version: master

- name: ensure zsh custom dir exists
  ansible.builtin.file:
    path: "~/.config/ohmyzsh/custom/{{ item }}"
    mode: 0750
    state: directory
  loop:
    - plugins
    - themes
    - completions

- name: install oh-my-zsh customizations
  ansible.builtin.copy:
    src: custom/
    dest: "~/.config/ohmyzsh/custom"
    mode: preserve

- name: install powerlvl10k prompt
  ansible.builtin.git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: "~/.config/ohmyzsh/custom/themes/powerlevel10k"
    version: master

- name: copy the p10k config
  ansible.builtin.copy:
    src: p10k.zsh
    dest: "~/.p10k.zsh"
    mode: 0640

- name: install fzf-tab zsh plugin
  ansible.builtin.git:
    repo: https://github.com/Aloxaf/fzf-tab
    dest: "~/.config/ohmyzsh/custom/plugins/fzf-tab"
    version: master

- name: copy zshrc
  ansible.builtin.template:
    src: zshrc.j2
    dest: "~/.zshrc"
    mode: 0640
