---
- name: Ensure kitty config directory exists
  ansible.builtin.file:
    name: "~/.config/kitty"
    state: directory
    mode: 0750

- name: Copy themes directory
  ansible.builtin.copy:
    src: "themes"
    dest: "~/.config/kitty/themes"
    mode: 0640

- name: Create kitty config
  ansible.builtin.template:
    src: kitty.conf.j2
    dest: "~/.config/kitty/kitty.conf"
    mode: 0640
  notify: Reload kitty config
