---
# tasks file for minimal_workstation

- name: Make sure wheel group exists
  ansible.builtin.group:
    name: "wheel"
    state: present
  become: true
- name: Create the user
  ansible.builtin.user:
    name: "{{ user.name }}"
    comment: "{{ user.full_name }}"
    uid: 1000
    groups:
      - wheel
    create_home: true
    shell: /bin/zsh
    state: present
  become: true

- name: Allow for passwordless sudo for {{ user.name }}
  ansible.builtin.copy:
    content: "{{ user.name }} ALL=(ALL:ALL) NOPASSWD: ALL"
    dest: "/etc/sudoers.d/{{ user.name }}_nopasswd"
    mode: 0440
  become: true

- name: Install base packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: latest
  loop: "{{ base_packages }}"
  become: true

- name: Setup neovim
  ansible.builtin.import_tasks: "nvim.yml"
  become: true
  become_user: "{{ user.name }}"

- name: Define custom profile
  ansible.builtin.copy:
    src: system_config/profile
    dest: "{{ user_home }}/.profile"
  become: true
  become_user: "{{ user.name }}"
