---

- name: install oh my zsh
  ansible.builtin.git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: "{{ user_home }}/.oh-my-zsh"
    depth: 1
    version: master

- name: ensure zsh custom dir exists
  file:
    path: "{{ config_dir }}/ohmyzsh/custom/{{ item }}"
    owner: "{{ user.name }}"
    group: users
    state: directory
  loop:
    - plugins
    - themes
    - completions

- name: install oh-my-zsh customizations
  ansible.builtin.copy:
    src: zsh/custom/
    dest: "{{ config_dir }}/ohmyzsh/custom"
    owner: "{{ user.name }}"
    group: users
    mode: preserve

- name: install powerlvl10k prompt
  ansible.builtin.git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: "{{ config_dir }}/ohmyzsh/custom/themes/powerlevel10k"
    version: master

- name: copy the p10k config
  ansible.builtin.copy:
    src: zsh/p10k.zsh
    dest: "{{ user_home }}/.p10k.zsh"

- name: install fzf-tab zsh plugin
  ansible.builtin.git:
    repo: https://github.com/Aloxaf/fzf-tab
    dest: "{{ config_dir }}/ohmyzsh/custom/plugins/fzf-tab"
    version: master

- name: copy zshrc
  ansible.builtin.copy:
    src: zsh/zshrc
    dest: "{{ user_home }}/.zshrc"
