---
# tasks file for cli_workstation
- name: Add Kubernetes repository
  ansible.builtin.yum_repository:
    name: "Kubernetes"
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    enabled: True
    state: present
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    description: Official google repository for K8S
  become: True

- name: Install Kubectl
  ansible.builtin.package:
    name: kubectl
    state: latest
  become: True

- name: Install kubectl completion
  ansible.builtin.shell:
    cmd: "kubectl completion zsh > /usr/share/zsh/site-functions/_kubectl"
    creates: /usr/share/zsh/site-functions/_kubectl
  become: True