---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
platforms:
  - name: instance
    box: "fedora/36-beta-cloud-base"
    cpus: 4
    memory: 4096
provisioner:
  name: ansible
  playbooks:
    converge: ../../../../minimal_workstation.yml
verifier:
  name: ansible
